CREATE TABLE iam_company
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code VARCHAR(64) NOT NULL,
    company_name VARCHAR(128) NOT NULL,
    legal_name VARCHAR(128) NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_comp_stat CHECK (status IN (0, 1))
);

CREATE TABLE iam_subsidiary
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    subsidiary_code VARCHAR(64) NOT NULL,
    subsidiary_name VARCHAR(128) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sub_comp FOREIGN KEY (company_id) REFERENCES iam_company (id),
    CONSTRAINT chk_sub_stat CHECK (status IN (0, 1))
);

CREATE TABLE iam_department
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    subsidiary_id BIGINT NULL,
    parent_id BIGINT NULL,
    department_code VARCHAR(64) NOT NULL,
    department_name VARCHAR(128) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dept_comp FOREIGN KEY (company_id) REFERENCES iam_company (id),
    CONSTRAINT fk_dept_sub FOREIGN KEY (subsidiary_id) REFERENCES iam_subsidiary (id),
    CONSTRAINT fk_dept_par FOREIGN KEY (parent_id) REFERENCES iam_department (id),
    CONSTRAINT chk_dept_stat CHECK (status IN (0, 1))
);

CREATE TABLE iam_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    email VARCHAR(128) NULL,
    phone VARCHAR(32) NULL,
    display_name VARCHAR(64) NULL,
    user_type VARCHAR(32) NOT NULL,
    company_id BIGINT NULL,
    subsidiary_id BIGINT NULL,
    department_id BIGINT NULL,
    is_active SMALLINT NOT NULL DEFAULT 1,
    is_staff SMALLINT NOT NULL DEFAULT 0,
    is_superuser SMALLINT NOT NULL DEFAULT 0,
    last_login TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_comp FOREIGN KEY (company_id) REFERENCES iam_company (id),
    CONSTRAINT fk_user_sub FOREIGN KEY (subsidiary_id) REFERENCES iam_subsidiary (id),
    CONSTRAINT fk_user_dept FOREIGN KEY (department_id) REFERENCES iam_department (id),
    CONSTRAINT chk_user_type CHECK (user_type IN ('PERSONAL', 'ENTERPRISE')),
    CONSTRAINT chk_user_act CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_user_staff CHECK (is_staff IN (0, 1)),
    CONSTRAINT chk_user_super CHECK (is_superuser IN (0, 1))
);

CREATE TABLE iam_permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(128) NOT NULL,
    permission_name VARCHAR(128) NOT NULL,
    permission_type VARCHAR(32) NOT NULL,
    parent_id BIGINT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_perm_par FOREIGN KEY (parent_id) REFERENCES iam_permission (id),
    CONSTRAINT chk_perm_type CHECK (permission_type IN ('MENU', 'ACTION', 'DATA')),
    CONSTRAINT chk_perm_stat CHECK (status IN (0, 1))
);

CREATE TABLE iam_role
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(128) NOT NULL,
    role_scope VARCHAR(32) NOT NULL,
    company_id BIGINT NULL,
    role_scope_company_id BIGINT GENERATED ALWAYS AS (COALESCE(company_id, 0)) STORED,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_role_comp FOREIGN KEY (company_id) REFERENCES iam_company (id),
    CONSTRAINT chk_role_scope CHECK (role_scope IN ('PERSONAL', 'ENTERPRISE')),
    CONSTRAINT chk_role_scope_company CHECK ( (role_scope = 'PERSONAL' AND company_id IS NULL) OR (role_scope = 'ENTERPRISE' AND company_id IS NOT NULL) ),
    CONSTRAINT chk_role_stat CHECK (status IN (0, 1))
);

CREATE TABLE iam_role_permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    data_scope VARCHAR(32) NULL,
    granted_by BIGINT NULL,
    expired_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES iam_role (id),
    CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES iam_permission (id),
    CONSTRAINT chk_rp_data_scope CHECK ( data_scope IS NULL OR data_scope IN ('SELF', 'DEPARTMENT', 'DEPARTMENT_TREE', 'SUBSIDIARY', 'COMPANY', 'ALL') ),
    CONSTRAINT fk_rp_grant FOREIGN KEY (granted_by) REFERENCES iam_user (id)
);

CREATE TABLE iam_user_role
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES iam_user (id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES iam_role (id)
);

CREATE TABLE iam_user_permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    effect VARCHAR(16) NOT NULL DEFAULT 'ALLOW',
    data_scope VARCHAR(32) NULL,
    granted_by BIGINT NULL,
    expired_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_up_user FOREIGN KEY (user_id) REFERENCES iam_user (id),
    CONSTRAINT fk_up_perm FOREIGN KEY (permission_id) REFERENCES iam_permission (id),
    CONSTRAINT fk_up_grant FOREIGN KEY (granted_by) REFERENCES iam_user (id),
    CONSTRAINT chk_up_data_scope CHECK ( data_scope IS NULL OR data_scope IN ('SELF', 'DEPARTMENT', 'DEPARTMENT_TREE', 'SUBSIDIARY', 'COMPANY', 'ALL') ),
    CONSTRAINT chk_up_effect CHECK (effect IN ('ALLOW', 'DENY'))
);

CREATE TABLE iam_department_permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    effect VARCHAR(16) NOT NULL DEFAULT 'ALLOW',
    data_scope VARCHAR(32) NULL,
    granted_by BIGINT NULL,
    expired_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dp_dept FOREIGN KEY (department_id) REFERENCES iam_department (id),
    CONSTRAINT fk_dp_perm FOREIGN KEY (permission_id) REFERENCES iam_permission (id),
    CONSTRAINT fk_dp_grant FOREIGN KEY (granted_by) REFERENCES iam_user (id),
    CONSTRAINT chk_dp_data_scope CHECK ( data_scope IS NULL OR data_scope IN ('SELF', 'DEPARTMENT', 'DEPARTMENT_TREE', 'SUBSIDIARY', 'COMPANY', 'ALL') ),
    CONSTRAINT chk_dp_effect CHECK (effect IN ('ALLOW', 'DENY'))
);

CREATE TABLE iam_subsidiary_permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subsidiary_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    effect VARCHAR(16) NOT NULL DEFAULT 'ALLOW',
    data_scope VARCHAR(32) NULL,
    granted_by BIGINT NULL,
    expired_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sp_sub FOREIGN KEY (subsidiary_id) REFERENCES iam_subsidiary (id),
    CONSTRAINT fk_sp_perm FOREIGN KEY (permission_id) REFERENCES iam_permission (id),
    CONSTRAINT fk_sp_grant FOREIGN KEY (granted_by) REFERENCES iam_user (id),
    CONSTRAINT chk_sp_data_scope CHECK ( data_scope IS NULL OR data_scope IN ('SELF', 'DEPARTMENT', 'DEPARTMENT_TREE', 'SUBSIDIARY', 'COMPANY', 'ALL') ),
    CONSTRAINT chk_sp_effect CHECK (effect IN ('ALLOW', 'DENY'))
);

CREATE TABLE iam_login_failure_lock
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    user_id BIGINT NULL,
    failed_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP NULL,
    last_failed_at TIMESTAMP NULL,
    last_client_ip VARCHAR(64) NULL,
    last_user_agent VARCHAR(512) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lfl_user FOREIGN KEY (user_id) REFERENCES iam_user (id)
);

CREATE TABLE iam_operation_audit
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT NULL,
    company_id BIGINT NULL,
    operation_type VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id BIGINT NULL,
    request_method VARCHAR(16) NULL,
    request_path VARCHAR(255) NULL,
    client_ip VARCHAR(64) NULL,
    user_agent VARCHAR(512) NULL,
    request_data JSONB NULL,
    before_data JSONB NULL,
    after_data JSONB NULL,
    extra_data JSONB NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    error_code INTEGER NULL,
    error_message VARCHAR(512) NULL,
    trace_id VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_operator FOREIGN KEY (operator_id) REFERENCES iam_user (id),
    CONSTRAINT fk_audit_company FOREIGN KEY (company_id) REFERENCES iam_company (id),
    CONSTRAINT chk_audit_status CHECK (status IN ('SUCCESS', 'FAILED'))
);

CREATE TABLE iam_user_device
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_id VARCHAR(128) NOT NULL,
    device_name VARCHAR(128) NOT NULL,
    device_type VARCHAR(32) NOT NULL,
    os_name VARCHAR(64) DEFAULT NULL,
    browser_name VARCHAR(64) DEFAULT NULL,
    fingerprint_hash VARCHAR(128) NOT NULL,
    trusted SMALLINT NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    first_login_at TIMESTAMP NOT NULL,
    last_active_at TIMESTAMP NOT NULL,
    last_client_ip VARCHAR(64) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ud_user FOREIGN KEY (user_id) REFERENCES iam_user (id)
);

CREATE TABLE iam_user_session
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    login_ip VARCHAR(64) DEFAULT NULL,
    user_agent TEXT DEFAULT NULL,
    risk_level SMALLINT NOT NULL DEFAULT 0,
    last_active_at TIMESTAMP NOT NULL,
    expired_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_us_user FOREIGN KEY (user_id) REFERENCES iam_user (id),
    CONSTRAINT fk_us_device FOREIGN KEY (device_id) REFERENCES iam_user_device (id)
);

CREATE TABLE iam_user_token
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NULL,
    refresh_token_hash CHAR(64) NOT NULL,
    access_jti VARCHAR(64) NULL,
    refresh_jti VARCHAR(64) NOT NULL,
    client_ip VARCHAR(64) NULL,
    user_agent VARCHAR(512) NULL,
    expired_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ut_user FOREIGN KEY (user_id) REFERENCES iam_user (id),
    CONSTRAINT fk_ut_session FOREIGN KEY (session_id) REFERENCES iam_user_session (id)
);

CREATE UNIQUE INDEX uk_comp_code ON iam_company (company_code);
CREATE INDEX idx_comp_created_by ON iam_company (created_by);
CREATE INDEX idx_comp_updated_by ON iam_company (updated_by);
CREATE UNIQUE INDEX uk_sub_code ON iam_subsidiary (subsidiary_code);
CREATE INDEX idx_sub_comp_id ON iam_subsidiary (company_id);
CREATE INDEX idx_sub_created_by ON iam_subsidiary (created_by);
CREATE INDEX idx_sub_updated_by ON iam_subsidiary (updated_by);
CREATE UNIQUE INDEX uk_dept_code ON iam_department (department_code);
CREATE INDEX idx_dept_comp_id ON iam_department (company_id);
CREATE INDEX idx_dept_sub_id ON iam_department (subsidiary_id);
CREATE INDEX idx_dept_par_id ON iam_department (parent_id);
CREATE INDEX idx_dept_created_by ON iam_department (created_by);
CREATE INDEX idx_dept_updated_by ON iam_department (updated_by);
CREATE UNIQUE INDEX uk_user_name ON iam_user (username);
CREATE UNIQUE INDEX uk_user_email ON iam_user (email);
CREATE UNIQUE INDEX uk_user_phone ON iam_user (phone);
CREATE INDEX idx_user_type ON iam_user (user_type);
CREATE INDEX idx_user_comp_id ON iam_user (company_id);
CREATE INDEX idx_user_sub_id ON iam_user (subsidiary_id);
CREATE INDEX idx_user_dept_id ON iam_user (department_id);
CREATE INDEX idx_user_created_by ON iam_user (created_by);
CREATE INDEX idx_user_updated_by ON iam_user (updated_by);
CREATE UNIQUE INDEX uk_perm_code ON iam_permission (permission_code);
CREATE INDEX idx_perm_par_id ON iam_permission (parent_id);
CREATE INDEX idx_perm_created_by ON iam_permission (created_by);
CREATE INDEX idx_perm_updated_by ON iam_permission (updated_by);
CREATE UNIQUE INDEX uk_role_scope_company_code ON iam_role (role_scope, role_scope_company_id, role_code);
CREATE INDEX idx_role_scope ON iam_role (role_scope);
CREATE INDEX idx_role_company_id ON iam_role (company_id);
CREATE INDEX idx_role_created_by ON iam_role (created_by);
CREATE INDEX idx_role_updated_by ON iam_role (updated_by);
CREATE UNIQUE INDEX uk_rp_role_perm ON iam_role_permission (role_id, permission_id);
CREATE INDEX idx_rp_perm_id ON iam_role_permission (permission_id);
CREATE INDEX idx_rp_data_scope ON iam_role_permission (data_scope);
CREATE INDEX idx_rp_grant_id ON iam_role_permission (granted_by);
CREATE INDEX idx_rp_exp_at ON iam_role_permission (expired_at);
CREATE INDEX idx_rp_created_by ON iam_role_permission (created_by);
CREATE INDEX idx_rp_updated_by ON iam_role_permission (updated_by);
CREATE UNIQUE INDEX uk_user_role ON iam_user_role (user_id, role_id);
CREATE INDEX idx_ur_role_id ON iam_user_role (role_id);
CREATE INDEX idx_ur_created_by ON iam_user_role (created_by);
CREATE INDEX idx_ur_updated_by ON iam_user_role (updated_by);
CREATE UNIQUE INDEX uk_up_user_perm ON iam_user_permission (user_id, permission_id);
CREATE INDEX idx_up_perm_id ON iam_user_permission (permission_id);
CREATE INDEX idx_up_data_scope ON iam_user_permission (data_scope);
CREATE INDEX idx_up_grant_id ON iam_user_permission (granted_by);
CREATE INDEX idx_up_exp_at ON iam_user_permission (expired_at);
CREATE INDEX idx_up_created_by ON iam_user_permission (created_by);
CREATE INDEX idx_up_updated_by ON iam_user_permission (updated_by);
CREATE UNIQUE INDEX uk_dp_dept_perm ON iam_department_permission (department_id, permission_id);
CREATE INDEX idx_dp_perm_id ON iam_department_permission (permission_id);
CREATE INDEX idx_dp_data_scope ON iam_department_permission (data_scope);
CREATE INDEX idx_dp_grant_id ON iam_department_permission (granted_by);
CREATE INDEX idx_dp_exp_at ON iam_department_permission (expired_at);
CREATE INDEX idx_dp_created_by ON iam_department_permission (created_by);
CREATE INDEX idx_dp_updated_by ON iam_department_permission (updated_by);
CREATE UNIQUE INDEX uk_sp_sub_perm ON iam_subsidiary_permission (subsidiary_id, permission_id);
CREATE INDEX idx_sp_perm_id ON iam_subsidiary_permission (permission_id);
CREATE INDEX idx_sp_data_scope ON iam_subsidiary_permission (data_scope);
CREATE INDEX idx_sp_grant_id ON iam_subsidiary_permission (granted_by);
CREATE INDEX idx_sp_exp_at ON iam_subsidiary_permission (expired_at);
CREATE INDEX idx_sp_created_by ON iam_subsidiary_permission (created_by);
CREATE INDEX idx_sp_updated_by ON iam_subsidiary_permission (updated_by);
CREATE UNIQUE INDEX uk_lfl_username ON iam_login_failure_lock (username);
CREATE INDEX idx_lfl_user_id ON iam_login_failure_lock (user_id);
CREATE INDEX idx_lfl_locked_until ON iam_login_failure_lock (locked_until);
CREATE INDEX idx_audit_operator_id ON iam_operation_audit (operator_id);
CREATE INDEX idx_audit_company_id ON iam_operation_audit (company_id);
CREATE INDEX idx_audit_resource ON iam_operation_audit (resource_type, resource_id);
CREATE INDEX idx_audit_operation_type ON iam_operation_audit (operation_type);
CREATE INDEX idx_audit_status ON iam_operation_audit (status);
CREATE INDEX idx_audit_trace_id ON iam_operation_audit (trace_id);
CREATE INDEX idx_audit_created_at ON iam_operation_audit (created_at);
CREATE UNIQUE INDEX uk_device_id ON iam_user_device (device_id);
CREATE UNIQUE INDEX uk_user_fingerprint ON iam_user_device (user_id, fingerprint_hash);
CREATE INDEX idx_ud_user_id ON iam_user_device (user_id);
CREATE INDEX idx_ud_user_fingerprint ON iam_user_device (user_id, fingerprint_hash);
CREATE INDEX idx_ud_last_active_at ON iam_user_device (last_active_at);
CREATE INDEX idx_ud_status ON iam_user_device (status);
CREATE UNIQUE INDEX uk_session_id ON iam_user_session (session_id);
CREATE INDEX idx_us_user_id ON iam_user_session (user_id);
CREATE INDEX idx_us_device_id ON iam_user_session (device_id);
CREATE INDEX idx_us_expired_at ON iam_user_session (expired_at);
CREATE INDEX idx_us_revoked_at ON iam_user_session (revoked_at);
CREATE INDEX idx_us_user_active ON iam_user_session (user_id, revoked_at, expired_at);
CREATE UNIQUE INDEX uk_ut_refresh_jti ON iam_user_token (refresh_jti);
CREATE UNIQUE INDEX uk_ut_refresh_token_hash ON iam_user_token (refresh_token_hash);
CREATE UNIQUE INDEX uk_ut_user_access_jti ON iam_user_token (user_id, access_jti);
CREATE INDEX idx_ut_user_id ON iam_user_token (user_id);
CREATE INDEX idx_ut_session_id ON iam_user_token (session_id);
CREATE INDEX idx_ut_access_jti ON iam_user_token (access_jti);
CREATE INDEX idx_ut_exp_at ON iam_user_token (expired_at);

INSERT INTO iam_permission
(permission_code, permission_name, permission_type, parent_id, status, created_at, updated_at)
VALUES ('iam:user:update_staff', '修改后台用户标识', 'ACTION', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('iam:user:update_superuser', '修改超级管理员标识', 'ACTION', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
