# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass

INFRA_IAM_DOMAIN = "iam"

DATA_SCOPE_SELF = "SELF"
DATA_SCOPE_DEPARTMENT = "DEPARTMENT"
DATA_SCOPE_DEPARTMENT_TREE = "DEPARTMENT_TREE"
DATA_SCOPE_SUBSIDIARY = "SUBSIDIARY"
DATA_SCOPE_COMPANY = "COMPANY"
DATA_SCOPE_ALL = "ALL"

DATA_SCOPE_VALUES = (
    DATA_SCOPE_SELF,
    DATA_SCOPE_DEPARTMENT,
    DATA_SCOPE_DEPARTMENT_TREE,
    DATA_SCOPE_SUBSIDIARY,
    DATA_SCOPE_COMPANY,
    DATA_SCOPE_ALL
)

DATA_SCOPE_CHOICES = (
    (DATA_SCOPE_SELF, "Self"),
    (DATA_SCOPE_DEPARTMENT, "Department"),
    (DATA_SCOPE_DEPARTMENT_TREE, "Department and child departments"),
    (DATA_SCOPE_SUBSIDIARY, "Subsidiary"),
    (DATA_SCOPE_COMPANY, "Company"),
    (DATA_SCOPE_ALL, "All")
)

DATA_SCOPE_LEVELS = {
    DATA_SCOPE_SELF: 10,
    DATA_SCOPE_DEPARTMENT: 20,
    DATA_SCOPE_DEPARTMENT_TREE: 30,
    DATA_SCOPE_SUBSIDIARY: 40,
    DATA_SCOPE_COMPANY: 50,
    DATA_SCOPE_ALL: 60
}

USER_TYPE_PERSONAL = "PERSONAL"
USER_TYPE_ENTERPRISE = "ENTERPRISE"

ROLE_SCOPE_PERSONAL = "PERSONAL"
ROLE_SCOPE_ENTERPRISE = "ENTERPRISE"

PERMISSION_TYPE_MENU = "MENU"
PERMISSION_TYPE_ACTION = "ACTION"
PERMISSION_TYPE_DATA = "DATA"

PERMISSION_EFFECT_ALLOW = "ALLOW"
PERMISSION_EFFECT_DENY = "DENY"

