# -*- coding: utf-8 -*-
"""PC-1 processor, audit, event and local plugin boundaries."""

from .audit import (
    AuditAction,
    AuditConsistency,
    AuditSink,
    AuditWriteOutcome,
    DeterministicTestAuditSink,
    LoggingAuditSink,
    ProcessorAuditBoundary,
    ProcessorAuditRecord,
)
from .contracts import (
    IdempotencyPrecheck,
    PROCESSOR_STAGE_ORDER,
    ProcessorAuthorization,
    ProcessorContext,
    ProcessorDependencies,
    ProcessorErrorMapper,
    ProcessorExecutionPolicy,
    ProcessorSafeSummary,
    ProcessorStage,
    ProcessorTraceReference,
    RateLimitEntry,
    ResponseFinalizer,
    RoutingPreparation,
)
from .event_bus import (
    EventBus,
    EventPublishReport,
    RuntimeEvent,
    SubscriberOutcome,
    SubscriberResult,
)
from .pipeline import (
    DefaultProcessorErrorMapper,
    InterfaceOnlyIdempotencyPrecheck,
    InterfaceOnlyRateLimitEntry,
    InterfaceOnlyRoutingPreparation,
    PassthroughResponseFinalizer,
    ProcessorExecutionResult,
    ProcessorPipeline,
    build_standard_stage_processors,
)
from .plugins import LocalPluginRegistry, LocalTrustedPlugin, PluginMetadata
from .registry import PipelineProcessor, ProcessorRegistration, ProcessorRegistry


__all__ = (
    "AuditAction",
    "AuditConsistency",
    "AuditSink",
    "AuditWriteOutcome",
    "DefaultProcessorErrorMapper",
    "DeterministicTestAuditSink",
    "EventBus",
    "EventPublishReport",
    "IdempotencyPrecheck",
    "InterfaceOnlyIdempotencyPrecheck",
    "InterfaceOnlyRateLimitEntry",
    "InterfaceOnlyRoutingPreparation",
    "LocalPluginRegistry",
    "LocalTrustedPlugin",
    "LoggingAuditSink",
    "PROCESSOR_STAGE_ORDER",
    "PassthroughResponseFinalizer",
    "PipelineProcessor",
    "PluginMetadata",
    "ProcessorAuditBoundary",
    "ProcessorAuditRecord",
    "ProcessorAuthorization",
    "ProcessorContext",
    "ProcessorDependencies",
    "ProcessorErrorMapper",
    "ProcessorExecutionPolicy",
    "ProcessorExecutionResult",
    "ProcessorPipeline",
    "ProcessorRegistration",
    "ProcessorRegistry",
    "ProcessorSafeSummary",
    "ProcessorStage",
    "ProcessorTraceReference",
    "RateLimitEntry",
    "ResponseFinalizer",
    "RoutingPreparation",
    "RuntimeEvent",
    "SubscriberOutcome",
    "SubscriberResult",
    "build_standard_stage_processors",
)
