# -*- coding: utf-8 -*-
from __future__ import annotations

from django.conf import settings

IAM_DB_ALIAS = settings.DATABASE_ROUTER_MAP.get("iam", "default")

DATA_SCOPE_SELF = "SELF"
DATA_SCOPE_DEPARTMENT = "DEPARTMENT"
DATA_SCOPE_DEPARTMENT_TREE = "DEPARTMENT_TREE"
DATA_SCOPE_SUBSIDIARY = "SUBSIDIARY"
DATA_SCOPE_COMPANY = "COMPANY"
DATA_SCOPE_ALL = "ALL"

DATA_SCOPE_VALUES = (
	DATA_SCOPE_SELF,
	DATA_SCOPE_DEPARTMENT,
	DATA_SCOPE_DEPARTMENT_TREE,
	DATA_SCOPE_SUBSIDIARY,
	DATA_SCOPE_COMPANY,
	DATA_SCOPE_ALL,
)

DATA_SCOPE_CHOICES = (
	(DATA_SCOPE_SELF, "仅本人"),
	(DATA_SCOPE_DEPARTMENT, "本部门"),
	(DATA_SCOPE_DEPARTMENT_TREE, "本部门及下级部门"),
	(DATA_SCOPE_SUBSIDIARY, "本子公司"),
	(DATA_SCOPE_COMPANY, "本公司"),
	(DATA_SCOPE_ALL, "全部"),
)

DATA_SCOPE_LEVELS = {
	DATA_SCOPE_SELF: 10,
	DATA_SCOPE_DEPARTMENT: 20,
	DATA_SCOPE_DEPARTMENT_TREE: 30,
	DATA_SCOPE_SUBSIDIARY: 40,
	DATA_SCOPE_COMPANY: 50,
	DATA_SCOPE_ALL: 60,
}

