# -*- coding: utf-8 -*-
"""P08 backend-neutral StateStore authority contract."""

from .authority import (
    STATE_AUTHORITY_BOUNDARIES,
    StateAccessScope,
    StateAtomicScope,
    StateAuthorityClassification,
    StateAuthorityKind,
    StateCallerCapability,
    StateNamespace,
    StateNamespaceKind,
    StateStoreCapabilities,
    StateStoreCapability,
    classify_state_authority,
)
from .model import (
    StateAppendResult,
    StateAssertion,
    StateConsistency,
    StateDocument,
    StateKey,
    StateMutation,
    StateMutationKind,
    StateReadResult,
    StateRecord,
    StateRevision,
    StateScanResult,
    StateStoreHealth,
    StateStoreHealthStatus,
    StateTransaction,
    StateTransactionResult,
)
from .store import StateStore, StateStoreLifecycleState
from .composition import create_state_store_provider
from .redis_provider import (
    EnvironmentStateStorePassword,
    FileStateStorePassword,
    NoStateStorePassword,
    RedisStateStoreOptions,
    RedisValkeyStateStore,
    StateStorePasswordSource,
    password_source_from_reference,
)


__all__ = (
    "STATE_AUTHORITY_BOUNDARIES",
    "StateAccessScope",
    "StateAppendResult",
    "StateAssertion",
    "StateAtomicScope",
    "StateAuthorityClassification",
    "StateAuthorityKind",
    "StateCallerCapability",
    "StateConsistency",
    "StateDocument",
    "StateKey",
    "StateMutation",
    "StateMutationKind",
    "StateNamespace",
    "StateNamespaceKind",
    "StateReadResult",
    "StateRecord",
    "StateRevision",
    "StateScanResult",
    "StateStore",
    "StateStoreCapabilities",
    "StateStoreCapability",
    "StateStoreHealth",
    "StateStoreHealthStatus",
    "StateStoreLifecycleState",
    "EnvironmentStateStorePassword",
    "FileStateStorePassword",
    "NoStateStorePassword",
    "RedisStateStoreOptions",
    "RedisValkeyStateStore",
    "StateStorePasswordSource",
    "StateTransaction",
    "StateTransactionResult",
    "classify_state_authority",
    "create_state_store_provider",
    "password_source_from_reference",
)
