# -*- coding: utf-8 -*-
"""P08 backend-neutral StateStore authority contract."""

from .authority import (
    STATE_AUTHORITY_BOUNDARIES,
    StateAccessScope,
    StateAtomicScope,
    StateAuthorityClassification,
    StateAuthorityKind,
    StateCallerCapability,
    StateNamespace,
    StateNamespaceKind,
    StateStoreCapabilities,
    StateStoreCapability,
    classify_state_authority,
)
from .model import (
    StateAppendResult,
    StateAssertion,
    StateConsistency,
    StateDocument,
    StateKey,
    StateMutation,
    StateMutationKind,
    StateOrderedIndexEntry,
    StateOrderedIndexCursor,
    StateOrderedIndexKey,
    StateOrderedIndexMutation,
    StateOrderedIndexMutationKind,
    StateOrderedIndexReadAssertion,
    StateOrderedIndexReadResult,
    StateReadResult,
    StateRecordReadAssertion,
    StateRecord,
    StateRevision,
    StateScanResult,
    StateStoreHealth,
    StateStoreHealthStatus,
    StateTransaction,
    StateTransactionResult,
    StateTransitionLogAppend,
)
from .store import (
    StateStore,
    StateStoreDeliveryRepositories,
    StateStoreLifecycleState,
    StateStoreRepository,
    StateStoreRepositoryRole,
)
from .composition import (
    StateStoreComposition,
    create_state_store_composition,
    create_state_store_provider,
)
from .redis_provider import (
    EnvironmentStateStorePassword,
    FileStateStorePassword,
    NoStateStorePassword,
    RedisStateStoreOptions,
    RedisValkeyStateStore,
    StateStorePasswordSource,
    password_source_from_reference,
)


__all__ = (
    "STATE_AUTHORITY_BOUNDARIES",
    "StateAccessScope",
    "StateAppendResult",
    "StateAssertion",
    "StateAtomicScope",
    "StateAuthorityClassification",
    "StateAuthorityKind",
    "StateCallerCapability",
    "StateConsistency",
    "StateDocument",
    "StateKey",
    "StateMutation",
    "StateMutationKind",
    "StateOrderedIndexEntry",
    "StateOrderedIndexCursor",
    "StateOrderedIndexKey",
    "StateOrderedIndexMutation",
    "StateOrderedIndexMutationKind",
    "StateOrderedIndexReadAssertion",
    "StateOrderedIndexReadResult",
    "StateNamespace",
    "StateNamespaceKind",
    "StateReadResult",
    "StateRecordReadAssertion",
    "StateRecord",
    "StateRevision",
    "StateScanResult",
    "StateStore",
    "StateStoreCapabilities",
    "StateStoreCapability",
    "StateStoreComposition",
    "StateStoreDeliveryRepositories",
    "StateStoreHealth",
    "StateStoreHealthStatus",
    "StateStoreLifecycleState",
    "StateStoreRepository",
    "StateStoreRepositoryRole",
    "EnvironmentStateStorePassword",
    "FileStateStorePassword",
    "NoStateStorePassword",
    "RedisStateStoreOptions",
    "RedisValkeyStateStore",
    "StateStorePasswordSource",
    "StateTransaction",
    "StateTransactionResult",
    "StateTransitionLogAppend",
    "classify_state_authority",
    "create_state_store_composition",
    "create_state_store_provider",
    "password_source_from_reference",
)
