# -*- coding: utf-8 -*-
"""Transport-independent logical connection lifecycle contracts."""

from __future__ import annotations

from .accepted import (
    ACCEPTED_HEARTBEAT_FIELDS,
    ACCEPTED_PAYLOAD_FIELDS,
    AcceptedHeartbeatPolicy,
    ConnectionAcceptedEnvelopeBuilder,
    ConnectionAdmissionActivator,
)
from .audit import (
    ConnectionAuditConsistency,
    ConnectionAuditKind,
    ConnectionAuditOutcome,
    ConnectionLifecycleAuditBoundary,
    ConnectionLifecycleAuditEvent,
    ConnectionLifecycleAuditSink,
    ConnectionLifecycleAuditSnapshot,
    DeterministicTestConnectionAuditSink,
)
from .authentication import (
    AuthenticatedHello,
    ConnectionHandshakeAuthenticator,
)
from .binding import (
    LogicalConnectionTransportMap,
    LogicalSessionIdentityFactory,
    LogicalTransportMappingSnapshot,
    NetworkPathBinding,
    TransportSessionBinding,
)
from .drain import (
    DRAIN_ALLOWED_MESSAGE_TYPES,
    ConnectionDrainEnvelopeHandler,
    ConnectionDrainService,
    DrainPolicy,
    DrainSnapshot,
    DrainingMessageDisposition,
    DrainingMessageGate,
)
from .handshake import ConnectionHelloReceiver
from .hello import (
    HELLO_EXTENSION_REGISTRY,
    HELLO_RESUME_NAMESPACE,
    HandshakeCredential,
    HelloClaimParser,
    HelloResumeRequest,
    ParsedHello,
    PendingHelloClaims,
)
from .heartbeat import (
    HEARTBEAT_ACK_PAYLOAD_FIELDS,
    HEARTBEAT_PAYLOAD_FIELDS,
    ConnectionHeartbeatService,
    EnvelopeHeartbeatOutcome,
    HeartbeatPolicy,
    HeartbeatSnapshot,
)
from .grace import (
    ReconnectGraceClaim,
    ReconnectGracePhase,
    ReconnectGracePolicy,
    ReconnectGraceService,
    ReconnectGraceSnapshot,
)
from .iam import (
    DeterministicTestIamAdapter,
    FailClosedHandshakeIamAdapter,
    HandshakeIamAdapter,
    HandshakeIamAuthority,
    HandshakeIamRequest,
    TestIamAction,
    TestIamOutcome,
)
from .index import (
    ConnectionIndexEntrySnapshot,
    LocalConnectionIndex,
    LocalConnectionIndexSnapshot,
)
from .session import (
    CapabilityPolicy,
    CapabilityRule,
    HandshakeSessionNegotiator,
    LogicalSessionIdentity,
    NegotiatedSession,
    P05_CAPABILITY_POLICY,
    SessionContext,
)
from .resume import (
    ConnectionEpochGate,
    ConnectionResumeCoordinator,
    EpochValidation,
    ResumedConnection,
)
from .reauth import (
    REAUTH_ACCEPTED_FIELDS,
    REAUTH_PAYLOAD_FIELDS,
    REAUTH_REJECTED_FIELDS,
    ConnectionReauthCoordinator,
    ConnectionReauthEnvelopeHandler,
    ParsedReauth,
    ReauthEnvelopeBuilder,
    ReauthFailureAction,
    ReauthRejectionReason,
    ReauthenticatedSession,
    SessionExpiryController,
    SessionExpiryPolicy,
    SessionExpirySnapshot,
)
from .security import (
    ConnectionSecurityAuditEvent,
    ConnectionSecurityAuditSink,
    DeterministicTestSecurityAuditSink,
    NonResumableCloseDecision,
    NonResumableCloseKind,
    NonResumableConnectionGuard,
    NonResumableConnectionSnapshot,
    NonResumablePublicError,
)
from .snapshot import (
    ConnectionCapabilityClass,
    SafeConnectionSnapshot,
    SafeConnectionSnapshotReader,
)
from .state import (
    LogicalConnectionCloseReason,
    LogicalConnectionState,
    LogicalConnectionStateMachine,
    LogicalConnectionStateSnapshot,
)


__all__ = (
    "ACCEPTED_HEARTBEAT_FIELDS",
    "ACCEPTED_PAYLOAD_FIELDS",
    "AcceptedHeartbeatPolicy",
    "AuthenticatedHello",
    "CapabilityPolicy",
    "CapabilityRule",
    "ConnectionAuditConsistency",
    "ConnectionAuditKind",
    "ConnectionAuditOutcome",
    "ConnectionCapabilityClass",
    "ConnectionHelloReceiver",
    "ConnectionHandshakeAuthenticator",
    "ConnectionHeartbeatService",
    "ConnectionAcceptedEnvelopeBuilder",
    "ConnectionAdmissionActivator",
    "ConnectionDrainService",
    "ConnectionDrainEnvelopeHandler",
    "ConnectionEpochGate",
    "ConnectionIndexEntrySnapshot",
    "ConnectionLifecycleAuditBoundary",
    "ConnectionLifecycleAuditEvent",
    "ConnectionLifecycleAuditSink",
    "ConnectionLifecycleAuditSnapshot",
    "ConnectionResumeCoordinator",
    "ConnectionReauthCoordinator",
    "ConnectionReauthEnvelopeHandler",
    "ConnectionSecurityAuditEvent",
    "ConnectionSecurityAuditSink",
    "DeterministicTestIamAdapter",
    "DeterministicTestConnectionAuditSink",
    "DeterministicTestSecurityAuditSink",
    "DRAIN_ALLOWED_MESSAGE_TYPES",
    "DrainPolicy",
    "DrainSnapshot",
    "DrainingMessageDisposition",
    "DrainingMessageGate",
    "EpochValidation",
    "FailClosedHandshakeIamAdapter",
    "HELLO_EXTENSION_REGISTRY",
    "HELLO_RESUME_NAMESPACE",
    "HEARTBEAT_ACK_PAYLOAD_FIELDS",
    "HEARTBEAT_PAYLOAD_FIELDS",
    "HandshakeCredential",
    "HandshakeIamAdapter",
    "HandshakeIamAuthority",
    "HandshakeIamRequest",
    "HandshakeSessionNegotiator",
    "HelloClaimParser",
    "HelloResumeRequest",
    "HeartbeatPolicy",
    "HeartbeatSnapshot",
    "LogicalConnectionCloseReason",
    "LogicalConnectionState",
    "LogicalConnectionStateMachine",
    "LogicalConnectionStateSnapshot",
    "LogicalConnectionTransportMap",
    "LogicalSessionIdentity",
    "LogicalSessionIdentityFactory",
    "LogicalTransportMappingSnapshot",
    "LocalConnectionIndex",
    "LocalConnectionIndexSnapshot",
    "NetworkPathBinding",
    "NegotiatedSession",
    "NonResumableCloseDecision",
    "NonResumableCloseKind",
    "NonResumableConnectionGuard",
    "NonResumableConnectionSnapshot",
    "NonResumablePublicError",
    "P05_CAPABILITY_POLICY",
    "ParsedReauth",
    "ParsedHello",
    "PendingHelloClaims",
    "ReconnectGraceClaim",
    "ReconnectGracePhase",
    "ReconnectGracePolicy",
    "ReconnectGraceService",
    "ReconnectGraceSnapshot",
    "REAUTH_ACCEPTED_FIELDS",
    "REAUTH_PAYLOAD_FIELDS",
    "REAUTH_REJECTED_FIELDS",
    "ReauthEnvelopeBuilder",
    "ReauthFailureAction",
    "ReauthRejectionReason",
    "ReauthenticatedSession",
    "ResumedConnection",
    "SafeConnectionSnapshot",
    "SafeConnectionSnapshotReader",
    "SessionContext",
    "SessionExpiryController",
    "SessionExpiryPolicy",
    "SessionExpirySnapshot",
    "EnvelopeHeartbeatOutcome",
    "TestIamAction",
    "TestIamOutcome",
    "TransportSessionBinding",
)
