# -*- coding: utf-8 -*-
from __future__ import annotations

from .base import NsEvermoreError, NsRuntimeError
from .cluster import (
    CLUSTER_ERROR_DEFINITIONS,
    NsRuntimeClusterCoordinationError,
    NsRuntimeClusterFencingError,
    NsRuntimeClusterStateError,
    NsRuntimeRoleAdmissionError,
    NsRuntimeStartupSecurityError,
)
from .common import (
    COMMON_ERROR_DEFINITIONS,
    NsConfigError,
    NsDependencyError,
    NsHttpClientError,
    NsStateError,
    NsValidationError,
)
from .delivery import (
    DELIVERY_ERROR_DEFINITIONS,
    NsRuntimeAckRejectedError,
    NsRuntimeBackpressureError,
    NsRuntimeDeferRejectedError,
    NsRuntimeDeliveryStateError,
    NsRuntimeNackRejectedError,
    NsRuntimeTargetUnavailableError,
)
from .metadata import NsErrorCategory, NsErrorDefinition, NsErrorSeverity
from .nack import (
    RUNTIME_NACK_REASON_ERROR_CODES,
    validate_runtime_nack_reason_error_codes,
)
from .payload_ref import (
    PAYLOAD_REF_ERROR_DEFINITIONS,
    NsRuntimePayloadRefChecksumMismatchError,
    NsRuntimePayloadRefDeniedError,
    NsRuntimePayloadRefExpiredError,
    NsRuntimePayloadRefInvalidError,
    NsRuntimePayloadRefValidationTimeoutError,
    NsRuntimePayloadRefValidationUnavailableError,
    NsRuntimePayloadRefVersionMismatchError,
)
from .protocol import (
    PROTOCOL_ERROR_DEFINITIONS,
    NsRuntimeAuthContextForgedError,
    NsRuntimeEnvelopeSchemaError,
    NsRuntimeProtocolError,
    NsRuntimeProtocolVersionError,
    NsRuntimeSourceForgedError,
    NsRuntimeTenantMismatchError,
    NsRuntimeUnauthorizedMessageTypeError,
    NsRuntimeUnsupportedMessageTypeError,
)
from .registry import (
    ALL_ERROR_DEFINITIONS,
    ERROR_REGISTRY,
    NsErrorRegistry,
    get_error_definition,
    get_error_definition_by_code,
    get_error_definition_by_numeric_code,
    list_error_definitions,
    validate_error_registry,
)


__all__ = [
    "ALL_ERROR_DEFINITIONS",
    "CLUSTER_ERROR_DEFINITIONS",
    "COMMON_ERROR_DEFINITIONS",
    "DELIVERY_ERROR_DEFINITIONS",
    "ERROR_REGISTRY",
    "NsConfigError",
    "NsDependencyError",
    "NsErrorCategory",
    "NsErrorDefinition",
    "NsErrorRegistry",
    "NsErrorSeverity",
    "NsEvermoreError",
    "NsHttpClientError",
    "NsRuntimeAckRejectedError",
    "NsRuntimeAuthContextForgedError",
    "NsRuntimeBackpressureError",
    "NsRuntimeClusterCoordinationError",
    "NsRuntimeClusterFencingError",
    "NsRuntimeClusterStateError",
    "NsRuntimeDeferRejectedError",
    "NsRuntimeDeliveryStateError",
    "NsRuntimeEnvelopeSchemaError",
    "NsRuntimeError",
    "NsRuntimeNackRejectedError",
    "NsRuntimePayloadRefChecksumMismatchError",
    "NsRuntimePayloadRefDeniedError",
    "NsRuntimePayloadRefExpiredError",
    "NsRuntimePayloadRefInvalidError",
    "NsRuntimePayloadRefValidationTimeoutError",
    "NsRuntimePayloadRefValidationUnavailableError",
    "NsRuntimePayloadRefVersionMismatchError",
    "NsRuntimeProtocolError",
    "NsRuntimeProtocolVersionError",
    "NsRuntimeRoleAdmissionError",
    "NsRuntimeSourceForgedError",
    "NsRuntimeStartupSecurityError",
    "NsRuntimeTargetUnavailableError",
    "NsRuntimeTenantMismatchError",
    "NsRuntimeUnauthorizedMessageTypeError",
    "NsRuntimeUnsupportedMessageTypeError",
    "NsStateError",
    "NsValidationError",
    "PAYLOAD_REF_ERROR_DEFINITIONS",
    "PROTOCOL_ERROR_DEFINITIONS",
    "RUNTIME_NACK_REASON_ERROR_CODES",
    "get_error_definition",
    "get_error_definition_by_code",
    "get_error_definition_by_numeric_code",
    "list_error_definitions",
    "validate_error_registry",
    "validate_runtime_nack_reason_error_codes",
]
